name: Update profile README stats
on:
  schedule:
    - cron: '0 2 * * *'   # daily at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip install -r scripts/requirements.txt
      - name: Update README with stats
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/update_stats.py
      - name: Commit & push if changed
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "chore: update GitHub stats [skip ci]"
            git push
          fi
