name: Update profile README stats
on:
  schedule:
    - cron: '0 2 * * *'   # daily at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci   # or pip install -r requirements.txt
      - name: Update README with stats
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/update_stats.js
      - name: Commit & push if changed
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "chore: update GitHub stats [skip ci]"
            git push
          fi
